=== SolovyovaAnya/db36/mephi.dtd
<!ELEMENT University (Fakulty)>
<!ATTLIST  University 
name CDATA #REQUIRED
phone CDATA #REQUIRED
street CDATA #REQUIRED>

<!ELEMENT Fakulty (Department)>
<!ATTLIST  Fakulty 
name CDATA #REQUIRED>

<!ELEMENT Department (Group, Group2)>
<!ATTLIST Department
name CDATA #REQUIRED>

<!ELEMENT Group (student+)>
<!ATTLIST  Group 
name CDATA #REQUIRED>

<!ELEMENT Group2 (student+)>
<!ATTLIST  Group2 
name CDATA #REQUIRED>

<!ELEMENT student (#PCDATA)>

=== SolovyovaAnya/db36/mephi.xml
<?xml version="1.0"?>
<!DOCTYPE University SYSTEM "mephi.dtd">
<University xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="mephi.xsd"
            name="Mephi" phone ="34-55-66" street="Moskvorechie">

   <Faculty name="cybernetics">
      <Department name="Invormation systems and technologies">
         <Group name="K5-361">
             <student> Anisimova Natasha</student>
               <student> Artemev Dmitriy</student>
           </Group>
              <Group name="K5-362">
               <student> Erohin Vladimir</student>
               <student> dasha</student>
           </Group>
          </Department>
    </Faculty>
</University>
